name: Docker Build And Push To Docker Hub

on:
#  schedule:
#    - cron: '0 10 * * *' # everyday at 10am
  push:
    branches:
      - 'dev'
    tags:
      - 'v*.*.*'
#  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Fetch tag
        run: |
          git fetch --tags --force

      - name: Create Release
        #        if: github.event_name == 'push'
        id: tag_data
        uses: ericcornelissen/git-tag-annotation-action@v1

      - name: The output
        run: echo ${{ steps.tag_data.outputs.git-tag-annotation }}

          #      - name: Docker meta
          #        id: docker_meta
          #        uses: crazy-max/ghaction-docker-meta@v1
          #        with:
          #          images: yuanmomo/action-test # list of Docker images to use as base name for tags
          #          tag-sha: false # add git short SHA as Docker tag
          #
          #      - name: Set up QEMU
          #        uses: docker/setup-qemu-action@v1
          #
          #      - name: Set up Docker Buildx
          #        uses: docker/setup-buildx-action@v1
          #
          #      - name: Login to DockerHub
          #        uses: docker/login-action@v1
          #        with:
          #          username: ${{ secrets.DOCKERHUB_USERNAME }}
          #          password: ${{ secrets.DOCKERHUB_TOKEN }}
          #
          #      - name: Build and push
          #        id: docker_build
          #        uses: docker/build-push-action@v2
          #        with:
          #          context: .
          #          push: true
          #          file: ./Dockerfile
          #          platforms: linux/amd64
          #          tags: ${{ steps.docker_meta.outputs.tags }}
          #          labels: ${{ steps.docker_meta.outputs.labels }}
          #
          #      - name: Image digest
          #        run: echo ${{ steps.docker_build.outputs.digest }}
